apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui--env--
  namespace: ns-posthub--env--
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui--env--
  template:
    metadata:
      labels:
        app: ui--env--
    spec:
      containers:
      - name: ui--env--
        image: __ImageTag__
        resources:
          requests:
              cpu: 250m
              memory: 350Mi
          limits:
            memory: "900Mi"
            cpu: "1100m"
        ports:
        - containerPort: 3000



---
kind: Service
apiVersion: v1
metadata:
  name:  ui-service--env--
  namespace: ns-posthub--env--
spec:
  selector:
    app:  ui--env--
  type:  ClusterIP
  ports:
  - name:  ui--env--
    port:  3000
    targetPort:  3000
    protocol:  TCP